In [1]:
import numpy as np

In [53]:
np.random.seed(0)
a = np.random.normal(0,1,[2,5])

In [59]:
print("a:",a,"\n"
     ,"升序a:",np.sort(a,axis=0),"\n"
     ,"arga:",np.argsort(a))

a: [[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]] 
 升序a: [[-0.97727788  0.40015721 -0.15135721 -0.10321885  0.4105985 ]
 [ 1.76405235  0.95008842  0.97873798  2.2408932   1.86755799]] 
 arga: [[1 2 0 4 3]
 [0 2 3 4 1]]


In [31]:
np.sort(a)

array([-0.97727788, -0.15135721, -0.10321885,  0.40015721,  0.4105985 ,
        0.95008842,  0.97873798,  1.76405235,  1.86755799,  2.2408932 ])

In [33]:
np.argsort(a)

array([5, 7, 8, 1, 9, 6, 2, 0, 4, 3], dtype=int64)